SCREEN_WIDTH = 600
SCREEN_HEIGHT = 450
SCREEN_TITLE = "Ninja Battle"

LEFT_VIEWPORT_MARGIN = 200
RIGHT_VIEWPORT_MARGIN = 200
TOP_VIEWPORT_MARGIN = 100
BOTTOM_VIEWPORT_MARGIN = 100

TOOLBAR_OBJECT_SIZE = 50
